### ISSUE TITLE
Repository clean-up

### ISSUE THREAD

**Issue by Siccity** [Eldemarkki/Marching-Cubes-Improved#1]
Hello!

I watched your video on youtube and checked out your plugin. It works really well! However i have one big gripe with it - the project it very messy. Here's my proposal:

1) Move all assets from Marching-Cubes-Improved up into the root, and delete the rest (Logs, ProjectSettings, .vscode). Your project files aren't needed.
2) Delete Rider plugin as it has nothing to do with the marching cubes implementation.
3) Make an Examples folder and move all files that aren't an absolute neccessary part of core functionality into that folder (SampleScene, FreeCam.cs, TerrainEditor.cs, FastNoise.cs, DensityGenerator.cs etc.)
4) Use namespaces. Especially important when you're using class names such as "World" and "Utils".
5) If "World" is part of the core, don't let it refer to anything in the examples folder. The Examples folder should be optional and deleteable. If you need something to generate a world on awake in the sample scene, do it in a separate script. This also helps to showcase how a user would do it.
6) Is the Prefabs/Chunk used at all? If not, remove it.

Doing like this will help users navigate your project much easier, as well as enabling the ability to clone your repo directly into their project so they can start using it.

**Comment by Eldemarkki** [comment]
Hey! Thanks for this suggestion! I agree it is quite messy, and should definitely be cleaned up. I'm a little busy this week but I will get started on this as soon as possible.
